### ISSUE TITLE
if at least one peer is dialable, the connection should work

### ISSUE THREAD

**Issue by MangoIV** [ethersync/ethersync#151] opened 2024-08-24 14:25 UTC
I want to communicate by using one peer as the "server" and then multiple peers connecting to it. I open the port on the initial peer and then try to connect to it by using `daemon --peer`. 

Running with `-d` reveals, that this fails, namely, at the central peer (the dialable peer): 

```
14:21:06 DEBUG ThreadId(02) Swarm::poll: libp2p_tcp: Incoming connection from remote at local remote_address= local_address=
14:21:06 DEBUG ThreadId(02) ethersync::peer: event=IncomingConnection { connection_id: ConnectionId(1), local_addr: "", send_back_addr: "" }
14:21:06 DEBUG ThreadId(03) Swarm::poll: libp2p_swarm: Incoming connection failed: Transport(Other(Custom { kind: Other, error: Other(Right(Left(Right(Select(ProtocolError(IoError(Custom { kind: InvalidData, error: "Maximum frame length exceeded" }))))))) }))
14:21:06 DEBUG ThreadId(03) ethersync::peer: event=IncomingConnectionError { connection_id: ConnectionId(1), local_addr: "", send_back_addr: "", error: Transport(Other(Custom { kind: Other, error: Other(Right(Left(Right(Select(ProtocolError(IoError(Custom { kind: InvalidData, error: "Maximum frame length exceeded" }))))))) })) }
``` 

and on the peer running with `--peer`: 

```
14:21:06 DEBUG ThreadId(02) Transport::dial{address=}: libp2p_core::upgrade::apply: Failed to upgrade outbound stream upgrade=/noise
14:21:06 DEBUG ThreadId(02) Swarm::poll: libp2p_swarm: Connection attempt to peer failed with Transport([("", Other(Custom { kind: Other, error: Other(Right(Left(Right(Apply(Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))))) }))]). peer=
14:21:06 DEBUG ThreadId(02) ethersync::peer: event=OutgoingConnectionError { connection_id: ConnectionId(1), peer_id: Some(PeerId("")), error: Transport([("", Other(Custom { kind: Other, error: Other(Right(Left(Right(Apply(Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))))) }))]) }
```

I have removed all the ipaddresses/ ports/ etc.

**Comment by zormit** [comment] 2024-08-26 20:10
This one might be hard to reproduce with the given information.
Did you try this locally or through the internet?

I'm not sure I understand what you're getting at with the title "if at least one peer is diable....".

Currently we don't have any smart peer to peer logic and we also just use a ["cloud peer"](https://ethersync.github.io/ethersync/use-cases/shared-notes.html). Is your network layout more complex than a "fan out" from one cloud peer?

**Comment by MangoIV** [comment] 2024-08-26 20:16
through the internet, so not local. 

I don't think I have a setup much different to the "cloud peer" scenario described - is there anything else I might be missing for that scenario to work?

**Comment by zormit** [comment] 2024-08-26 20:38
yeah I have an idea. Two things to check that need to be correct for a successful connection:
- the secret (either provided through the [configuration](https://ethersync.github.io/ethersync/features/configuration.html) file or the `--secret` flag)
- the multiaddress needs to have the correct public key

---

 i just tried this:

```bash
ethersync daemon -d --port 4242 --secret local-playground-test playground
```
(if you don't provide the `--secret` flag at the host, it's generated for you. maybe you missed it in the logs?)

and then connecting to it with a wrong secret

```bash
ethersync daemon --peer /ip4/192.168.158.85/tcp/4242/p2p/12D3KooWL3RKvJssbd1caTufwJ3WjKNHPTDuFUjadzjThbQw1U6Q --secret local-playground-WRONG -d
```

which seems to result in a similar error that you're getting. (something with "Maximum frame length exceeded")

---

As for the multiaddress: if you can live without the "trust" part (certainly for debugging and just because it's easier to double check) you can also try dropping the public key part:
`ethersync daemon --peer /ip4/192.168.158.85/tcp/4242 --secret local-playground-test -d`

**Comment by zormit** [comment] 2024-08-26 20:41
Let me know if that helped!

FWIW, I've just increased the priority of #107, as it's really not user friendly at all to just swallow this stuff and not being able to report on a wrong secret.

**Comment by blinry** [comment] 2024-09-09 13:24
Curious if you were able to get your "cloud peer" setup to work, @MangoIV!

We revamped the documentation for it last week, if it's helpful: https://ethersync.github.io/ethersync/shared-notes.html

**Comment by MangoIV** [comment] 2024-09-10 08:18
I will try this week, sorry, didn't have the chance yet :)

**Comment by blinry** [comment] 2024-11-14 09:39
We'll close this for now – let us know if you have more troubles, @MangoIV! :)

**Closed by blinry** 2024-11-14 09:39 UTC
Labels: bug

**Comment by MangoIV** [comment] 2024-11-14 15:05
Oh yeah I got this to work but forgot to report. Thank you
