### ISSUE TITLE
Document safety concept with attack vectors

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#99] opened 2024-08-08 09:13 UTC
- [ ] write the documentation
- [ ] cross-check with ROS!

**Comment by blinry** [comment] 2024-08-21 14:51
Duplicate of #117, right?

**Closed by blinry** 2024-08-21 14:51 UTC

**Comment by zormit** [comment] 2024-08-26 11:00
@blinry well, almost, but it's fine for now. I think the idea of "concept of attack vectors" is / can be viewed much broader than just the ADR on libp2p. While it's not the same angle we have included most of the ideas in the ADR, I gues.
